import type { Metadata } from "next";
import "./globals.css";
import "./global-icons.css";
import {AppRouterCacheProvider} from "@mui/material-nextjs/v13-appRouter";
import {ThemeProvider} from "@mui/material";
import {theme} from "@/theme";
import Sidebar from "@/app/components/layout/sidebar";
import Header from "@/app/components/layout/header";
import {vazirFaFont, vazirFont, yekanBakhFont} from "@/fonts";
import BootstrapClient from "@/app/components/core/BootstrapClient";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa">
      <head>
        <link rel="stylesheet" href="https://cdn.rtlcss.com/bootstrap/v4.5.3/css/bootstrap.min.css"></link>
      </head>

      <body className={`${vazirFaFont.variable} ${vazirFont.variable} ${yekanBakhFont.variable} font-vazir-fa`} dir={"rtl"}>
          <AppRouterCacheProvider>
            <ThemeProvider theme={theme}>
              <div className={"d-flex h-100"}>
                <Sidebar/>

                <div className={'flex-fill'}>
                  <Header/>

                  <main>
                    {children}
                  </main>
                </div>
              </div>
            </ThemeProvider>
          </AppRouterCacheProvider>
          <BootstrapClient/>
      </body>
    </html>
  );
}
